### ISSUE TITLE
Openmrs data location

### ISSUE THREAD

**Issue by dharmeshpurohit** [karrtikiyer-tw/bahmni-eda#1]
Hi Kartik,

I am have downloaded data and created my local mysql instance. When I try to see what all type of diagnosis I have in the obs table I found none. I downloaded large-demo-data.sql. Is possible for you which dataset are you using for your analysis or you can share the dataset location ?

Thanks 

Dharmesh

**Comment by karrtikiyer-tw** [comment]
Hi Dharmesh,

I think it is better for you to get in touch with people from Bahmni team on Open MRS forum. They should be able to guide you better to get a DB that has the diagnosis in obs table.
